//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exchange
    {
        public string ExchangeCode { get; set; }
        public string ExchangeName { get; set; }
        public string CountryID { get; set; }
        public System.DateTime UpdateDate { get; set; }
    }
}
