//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SubsidiariesEntities1 : DbContext
    {
        public SubsidiariesEntities1()
            : base("name=SubsidiariesEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Association> Associations { get; set; }
        public virtual DbSet<AssociationType> AssociationTypes { get; set; }
        public virtual DbSet<CompanyName> CompanyNames { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<Exchange> Exchanges { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Registration_dbo> Registration_dbo { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
